require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'deekay_multi_env_test',
'Debug.Staysure' => :debug,
'Release.Staysure' => :release,
'Debug.Avanti' => :debug,
'Release.Avanti' => :release

target 'deekay_multi_env_test' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'deekay_multi_env_testTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'deekay_multi_env_test-tvOS' do
  # Pods for deekay_multi_env_test-tvOS

  target 'deekay_multi_env_test-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
